[[pages]]
path = "pages/set_profile.py"
name = "Start"
icon = "👤"

[[pages]]
path = "pages/slim_chat.py"
name = "Chat"
icon = "💬"

[[pages]]
path = "pages/submit_feedback.py"
name = "Feedback"
icon = "🤔"